In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
def PCA(Data):
    '''Data (n_feature, n_sample)'''
    Data_z = Data - np.mean(Data, axis = 1)[:, np.newaxis] # zero-mean data
    S = np.dot(Data_z, Data_z.T) / Data_z.shape[1]
    eigenVal, eigenVec = np.linalg.eig(S)
    return eigenVal, eigenVec, Data_z

In [23]:
def offset_PCA(Data):
    '''Data (n_feature, n_sample)'''
    Data_z = Data - np.mean(Data, axis = 1)[:, np.newaxis] # zero-mean data
    S = (np.dot(Data_z[:,:-1], Data_z[:,1:].T) + np.dot(Data_z[:,1:], Data_z[:,:-1].T)) / (2*Data_z.shape[1]-2)
    eigenVal, eigenVec = np.linalg.eig(S)
    return eigenVal, eigenVec, Data_z

In [ ]:
def plot_eigenSpectrum(eigenVal):
    plt.plot(np.arange(eigenVal.shape[0])+1, np.sqrt(eigenVal), '.-')
    plt.ylabel('$\\sqrt{\\lambda_i}$')
    plt.xlabel('i')
    plt.title('Eigenvalue Spectrum')
    print('Percentage of overall variance captured by the top 3 principal components: ')
    for i in range(3):
        print(f\"{i+1}: {eigenVal[i]/np.sum(eigenVal)*100: .2f}%\")

In [18]:
a = np.arange(1,6)
b = np.repeat(a,4).reshape(5,4).T
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
np.dot(b[:,1:],b[:,:-1].T)

array([[40, 40, 40, 40],
       [40, 40, 40, 40],
       [40, 40, 40, 40],
       [40, 40, 40, 40]])

In [22]:
b[:,1:],b[:,:-1].T

(array([[2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5]]),
 array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]]))

In [31]:
offset_PCA(b)

(array([0., 4., 0., 0.]),
 array([[-8.66025404e-01,  5.00000000e-01, -2.77555756e-17,
         -2.77555756e-17],
        [ 2.88675135e-01,  5.00000000e-01, -5.77350269e-01,
         -5.77350269e-01],
        [ 2.88675135e-01,  5.00000000e-01,  7.88675135e-01,
         -2.11324865e-01],
        [ 2.88675135e-01,  5.00000000e-01, -2.11324865e-01,
          7.88675135e-01]]),
 array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]]))

In [32]:
eigenValue, eigenVector, avg = PCA(b)

In [33]:
z = eigenVector.T.dot(avg)

In [34]:
eigenVector.shape, avg.shape

((4, 4), (4, 5))

In [35]:
b.shape

(4, 5)

In [36]:
eigenVector.dot(z),avg

(array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]]),
 array([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]]))